name: ItemPickupNotifier
version: 2.0
main: me.boomboompower.itempickupnotifier.Main
author: boomboompower
description: Notifies the player when they pickup an item!
website: boomboompower.weebly.com
